# Generated by Django 4.0.5 on 2022-07-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=30)),
                ('model_code', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
                ('working_condition', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.employee')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.sample')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='samples',
            field=models.ManyToManyField(related_name='employees', through='portal.Ownership', to='portal.sample'),
        ),
    ]
